apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-06-30T22:15:20Z"
  labels:
    app: easytally
  name: easytally
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: easytally
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: easytally
    spec:
      containers:
      - image: ghcr.io/djnotes/easytally:main
        imagePullPolicy: Always
        name: easytally
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi      
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: API_ID
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: api-id
          - name: API_HASH
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: api-hash
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: easytally-bot-token
        volumeMounts:
         - mountPath: /app/session
           name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: easytally-session-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

      
status:
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1


