version: "3.9"
services:
  app:
    image: ghcr.io/djnotes/easytally:latest
    build:
      context: . 
      dockerfile: ./Containerfile
    
    
    volumes:
      - type: bind
        source: . 
        target: /app
    
    ports:
      - 6789:5678
    
    
    
    env_file:
      - env.ini
      
  node1:
    image: docker.io/library/cassandra:4.1.3
    volumes:
      - easytallydb:/var/lib/cassandra
    env_file:
      - env.ini
  
  node2:
    image: docker.io/library/cassandra:4.1.3
    volumes:
      - easytallydb:/var/lib/cassandra
    env_file:
      - env.ini

volumes:
  easytallydb: {}
