apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-30T22:15:20Z"
  generation: 1
  labels:
    app: easytally
  name: easytally
  namespace: default
  resourceVersion: "8467"
  uid: 798abff3-49ad-4839-8590-3b273b444f79
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: easytally
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: easytally
    spec:
      containers:
      - image: ghcr.io/djnotes/easytally:main
        imagePullPolicy: IfNotPresent
        name: easytally
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-06-30T22:15:20Z"
    lastUpdateTime: "2022-06-30T22:15:23Z"
    message: ReplicaSet "easytally-8599459f9b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-06-30T22:17:05Z"
    lastUpdateTime: "2022-06-30T22:17:05Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
